export const INITIAL_BADGES = [
  {
    id: "cheetah_speed",
    title: "Cheetah Sprint",
    description:
      "Fastest average time per question in a completed test (min 80% accuracy)",
    iconName: "Zap",
    emoji: "🐆",
    category: "speed",
    requirementDescription: "Lowest seconds / question record",
    unlocked: false,
  },
  {
    id: "deadshot_accuracy",
    title: "Deadshot Sniper",
    description: "Highest test accuracy record across official dodging tests",
    iconName: "Target",
    emoji: "🎯",
    category: "accuracy",
    requirementDescription: "Highest accuracy % record",
    unlocked: false,
  },
  {
    id: "apex_score",
    title: "Apex Grand Champion",
    description: "Highest single dodging test score achieved in the class",
    iconName: "Crown",
    emoji: "👑",
    category: "score",
    requirementDescription: "Highest single test score record",
    unlocked: false,
  },
  {
    id: "lightning_reaction",
    title: "Lightning Reaction",
    description: "Sub-1.5s ultra-speed response record on 10+ questions test",
    iconName: "Flame",
    emoji: "⚡",
    category: "speed",
    requirementDescription: "Fastest reaction speed record",
    unlocked: false,
  },
  {
    id: "streak_overlord",
    title: "Streak Overlord",
    description: "Longest active daily practice streak in the classroom",
    iconName: "Flame",
    emoji: "🔥",
    category: "streak",
    requirementDescription: "Highest active daily streak record",
    unlocked: false,
  },
  {
    id: "xp_titan",
    title: "XP Titan",
    description: "Highest total XP accumulated in the classroom",
    iconName: "Sparkles",
    emoji: "💎",
    category: "score",
    requirementDescription: "Highest total XP record",
    unlocked: false,
  },
  {
    id: "iron_wall",
    title: "Iron Wall Flawless",
    description: "Most 100% perfect (10/10) test clears without a single error",
    iconName: "Award",
    emoji: "🛡️",
    category: "accuracy",
    requirementDescription: "Most flawless 100% tests record",
    unlocked: false,
  },
  {
    id: "dodging_warlord",
    title: "Dodging Warlord",
    description: "Most official dodging tests completed overall",
    iconName: "Trophy",
    emoji: "⚔️",
    category: "dedication",
    requirementDescription: "Most tests completed record",
    unlocked: false,
  },
  {
    id: "supersonic_prodigy",
    title: "Supersonic Prodigy",
    description: "Fastest total test completion time with 90%+ accuracy",
    iconName: "Award",
    emoji: "🚀",
    category: "speed",
    requirementDescription: "Lowest total test duration record",
    unlocked: false,
  },
  {
    id: "the_centurion",
    title: "The Centurion",
    description:
      "Most total math questions answered correctly across all tests",
    iconName: "Award",
    emoji: "🌟",
    category: "dedication",
    requirementDescription: "Most math problems solved record",
    unlocked: false,
  },
];

export const INITIAL_QUEST_STAGES = [
  {
    id: "stage_1",
    stageNumber: 1,
    title: "Tables 2 to 5 Sprint",
    operation: "multiplication",
    difficulty: "rookie",
    description:
      "Master elementary multiplication tables 2, 3, 4, and 5 with high speed.",
    requiredXP: 0,
    targetQuestions: 8,
    starsEarned: 0,
    isUnlocked: true,
  },
  {
    id: "stage_2",
    stageNumber: 2,
    title: "Tables 6 to 9 Core Matrix",
    operation: "multiplication",
    difficulty: "explorer",
    description:
      "Conquer the tricky 6×, 7×, 8×, and 9× dodging table problems.",
    requiredXP: 60,
    targetQuestions: 10,
    starsEarned: 0,
    isUnlocked: false,
  },
  {
    id: "stage_3",
    stageNumber: 3,
    title: "Missing Factor Detective",
    operation: "missing_factor",
    difficulty: "explorer",
    description:
      "Find the missing multiplier in fast-paced dodging equations (e.g. ? × 8 = 56).",
    requiredXP: 150,
    targetQuestions: 10,
    starsEarned: 0,
    isUnlocked: false,
  },
  {
    id: "stage_4",
    stageNumber: 4,
    title: "Inverse Division Vault",
    operation: "division",
    difficulty: "explorer",
    description: "Reverse dodging tables to find quotients in record time.",
    requiredXP: 260,
    targetQuestions: 10,
    starsEarned: 0,
    isUnlocked: false,
  },
  {
    id: "stage_5",
    stageNumber: 5,
    title: "Tables 11 to 15 Heavyweights",
    operation: "multiplication",
    difficulty: "champion",
    description:
      "Advanced multiplication tables 11 through 15 with rapid calculation.",
    requiredXP: 400,
    targetQuestions: 12,
    starsEarned: 0,
    isUnlocked: false,
  },
  {
    id: "stage_6",
    stageNumber: 6,
    title: "Mixed Dodging Grand Prix (Boss Stage)",
    operation: "mixed",
    difficulty: "master",
    description:
      "The ultimate lightning dodging test mixing multiplication, division, and missing factors up to Table 20!",
    requiredXP: 650,
    targetQuestions: 15,
    starsEarned: 0,
    isUnlocked: false,
    isBossStage: true,
  },
];
